# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_SOLUTION_FILE: sirius-gcs.sln
  BUILD_PROJECT_NAME: sirius-gcs-tests
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Execute setup script
      run: .\setup\setup.bat

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ${{env.BUILD_SOLUTION_FILE}} /m /t:${{env.BUILD_PROJECT_NAME}} /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}}

  run-tests:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Run Tests
      run: .\out\bin\Release\sirius-gcs-tests.exe
